require("render-markdown").setup({
  enabled = true,
  file_types = { "markdown", "quarto" },
  completions = { lsp = { enabled = true } },
  win_options = {
    conceallevel = {
      default = 0,
      rendered = 2,
    },
  },
  heading = {
    enabled = true,
    atx = true,
    setext = true,
    sign = true,
    icons = { "# ", "## ", "### ", "#### ", "##### ", "###### " },
    position = "overlay",
    signs = { "󰫎 " },
    width = "full",
    left_margin = 0,
    left_pad = 0,
    right_pad = 0,
    min_width = 0,
    border = false,
    border_virtual = false,
    border_prefix = false,
    above = "▄",
    below = "▀",
    backgrounds = {
      "RenderMarkdownH1Bg",
      "RenderMarkdownH2Bg",
      "RenderMarkdownH3Bg",
      "RenderMarkdownH4Bg",
      "RenderMarkdownH5Bg",
      "RenderMarkdownH6Bg",
    },
    foregrounds = {
      "RenderMarkdownH1",
      "RenderMarkdownH2",
      "RenderMarkdownH3",
      "RenderMarkdownH4",
      "RenderMarkdownH5",
      "RenderMarkdownH6",
    },
    custom = {},
  },
  code = {
    enabled = true,
    sign = true,
    style = "normal",
    position = "right",
    language_pad = 0,
    disable_background = { "diff" },
    width = "block",
    left_pad = 0,
    right_pad = 0,
    min_width = 0,
    border = "thick",
    above = "▄",
    below = "▀",
    highlight = "RenderMarkdownCode",
    highlight_inline = "RenderMarkdownCodeInline",
  },
})
